<?xml version="1.0" encoding="utf-8"?><Database Name="SOTRE" Class="SOTREDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ANALIS-HP\SQLEXPRESS;Initial Catalog=SOTRE;Integrated Security=True" SettingsObjectName="SOTRE.Domain.Properties.Settings" SettingsPropertyName="SOTREConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="id_cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nm_logradouro" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="nm_bairro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nm_cep" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="cd_numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nm_complemento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cd_tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nm_cpf_cnpj" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nm_cidade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nm_longitude" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nm_latitude" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Viagem" Member="Viagems" ThisKey="id_cliente" OtherKey="cd_partida" Type="Viagem" />
      <Association Name="Cliente_Viagem1" Member="Viagems1" ThisKey="id_cliente" OtherKey="cd_destino" Type="Viagem" />
      <Association Name="Cliente_Pedido" Member="Pedidos" ThisKey="id_cliente" OtherKey="cd_cliente" Type="Pedido" />
      <Association Name="Cliente_Turno_Cliente" Member="Turno_Clientes" ThisKey="id_cliente" OtherKey="cd_cliente" Type="Turno_Cliente" />
      <Association Name="Tipo_Cliente_Cliente" Member="Tipo_Cliente" ThisKey="cd_tipo" OtherKey="id_tipo" Type="Tipo_Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Viagem" Member="Viagems">
    <Type Name="Viagem">
      <Column Name="id_caminho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_partida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_destino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_duracao" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cd_distancia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Viagem" Member="Cliente" ThisKey="cd_partida" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Cliente_Viagem1" Member="Cliente1" ThisKey="cd_destino" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Demanda" Member="Demandas">
    <Type Name="Demanda">
      <Column Name="id_demanda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_pedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="qtd_produto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Demanda" Member="Pedido" ThisKey="cd_pedido" OtherKey="id_pedido" Type="Pedido" IsForeignKey="true" />
      <Association Name="Produto_Demanda" Member="Produto" ThisKey="cd_produto" OtherKey="id_produto" Type="Produto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pedido" Member="Pedidos">
    <Type Name="Pedido">
      <Column Name="id_pedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Demanda" Member="Demandas" ThisKey="id_pedido" OtherKey="cd_pedido" Type="Demanda" />
      <Association Name="Cliente_Pedido" Member="Cliente" ThisKey="cd_cliente" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Status_Pedido_Pedido" Member="Status_Pedido" ThisKey="cd_status" OtherKey="id_status" Type="Status_Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Produto" Member="Produtos">
    <Type Name="Produto">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cd_duracao_descarga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_espaco_ocupado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nm_descricao" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Produto_Demanda" Member="Demandas" ThisKey="id_produto" OtherKey="cd_produto" Type="Demanda" />
    </Type>
  </Table>
  <Table Name="dbo.Status_Pedido" Member="Status_Pedidos">
    <Type Name="Status_Pedido">
      <Column Name="id_status" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Status_Pedido_Pedido" Member="Pedidos" ThisKey="id_status" OtherKey="cd_status" Type="Pedido" />
    </Type>
  </Table>
  <Table Name="dbo.Status_Veiculo" Member="Status_Veiculos">
    <Type Name="Status_Veiculo">
      <Column Name="id_status" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_descricao" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Status_Veiculo_Veiculo" Member="Veiculos" ThisKey="id_status" OtherKey="cd_status" Type="Veiculo" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_Cliente" Member="Tipo_Clientes">
    <Type Name="Tipo_Cliente">
      <Column Name="id_tipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_descricao" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Tipo_Cliente_Cliente" Member="Clientes" ThisKey="id_tipo" OtherKey="cd_tipo" Type="Cliente" />
    </Type>
  </Table>
  <Table Name="dbo.Turno" Member="Turnos">
    <Type Name="Turno">
      <Column Name="id_turno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_horaInicial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_horaFinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_trafego" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Turno_Turno_Cliente" Member="Turno_Clientes" ThisKey="id_turno" OtherKey="cd_turno" Type="Turno_Cliente" />
    </Type>
  </Table>
  <Table Name="dbo.Turno_Cliente" Member="Turno_Clientes">
    <Type Name="Turno_Cliente">
      <Column Name="id_turno_cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cd_turno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Turno_Cliente" Member="Cliente" ThisKey="cd_cliente" OtherKey="id_cliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Turno_Turno_Cliente" Member="Turno" ThisKey="cd_turno" OtherKey="id_turno" Type="Turno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nm_cpf" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="nm_nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nm_login" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nm_senha" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Veiculo" Member="Veiculos">
    <Type Name="Veiculo">
      <Column Name="id_veiculo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cd_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nm_nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="capacidade" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Status_Veiculo_Veiculo" Member="Status_Veiculo" ThisKey="cd_status" OtherKey="id_status" Type="Status_Veiculo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>