#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTRE.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOTRE")]
	public partial class SOTREDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaminho(Caminho instance);
    partial void UpdateCaminho(Caminho instance);
    partial void DeleteCaminho(Caminho instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDemanda(Demanda instance);
    partial void UpdateDemanda(Demanda instance);
    partial void DeleteDemanda(Demanda instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertTab_Tipo_Status(Tab_Tipo_Status instance);
    partial void UpdateTab_Tipo_Status(Tab_Tipo_Status instance);
    partial void DeleteTab_Tipo_Status(Tab_Tipo_Status instance);
    partial void InsertTab_Tipo_Status_Veiculo(Tab_Tipo_Status_Veiculo instance);
    partial void UpdateTab_Tipo_Status_Veiculo(Tab_Tipo_Status_Veiculo instance);
    partial void DeleteTab_Tipo_Status_Veiculo(Tab_Tipo_Status_Veiculo instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public SOTREDataContext() : 
				base(global::SOTRE.Domain.Properties.Settings.Default.SOTREConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Caminho> Caminho
		{
			get
			{
				return this.GetTable<Caminho>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculo
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Demanda> Demanda
		{
			get
			{
				return this.GetTable<Demanda>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedido
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produto
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Tab_Tipo_Status> Tab_Tipo_Status
		{
			get
			{
				return this.GetTable<Tab_Tipo_Status>();
			}
		}
		
		public System.Data.Linq.Table<Tab_Tipo_Status_Veiculo> Tab_Tipo_Status_Veiculo
		{
			get
			{
				return this.GetTable<Tab_Tipo_Status_Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Caminho")]
	public partial class Caminho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_caminho;
		
		private int _cd_partida;
		
		private int _cd_destino;
		
		private double _cd_duracao;
		
		private double _cd_distancia;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Cliente> _Cliente1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_caminhoChanging(int value);
    partial void Onid_caminhoChanged();
    partial void Oncd_partidaChanging(int value);
    partial void Oncd_partidaChanged();
    partial void Oncd_destinoChanging(int value);
    partial void Oncd_destinoChanged();
    partial void Oncd_duracaoChanging(double value);
    partial void Oncd_duracaoChanged();
    partial void Oncd_distanciaChanging(double value);
    partial void Oncd_distanciaChanged();
    #endregion
		
		public Caminho()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Cliente1 = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_caminho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_caminho
		{
			get
			{
				return this._id_caminho;
			}
			set
			{
				if ((this._id_caminho != value))
				{
					this.Onid_caminhoChanging(value);
					this.SendPropertyChanging();
					this._id_caminho = value;
					this.SendPropertyChanged("id_caminho");
					this.Onid_caminhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_partida", DbType="Int NOT NULL")]
		public int cd_partida
		{
			get
			{
				return this._cd_partida;
			}
			set
			{
				if ((this._cd_partida != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_partidaChanging(value);
					this.SendPropertyChanging();
					this._cd_partida = value;
					this.SendPropertyChanged("cd_partida");
					this.Oncd_partidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_destino", DbType="Int NOT NULL")]
		public int cd_destino
		{
			get
			{
				return this._cd_destino;
			}
			set
			{
				if ((this._cd_destino != value))
				{
					if (this._Cliente1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_destinoChanging(value);
					this.SendPropertyChanging();
					this._cd_destino = value;
					this.SendPropertyChanged("cd_destino");
					this.Oncd_destinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_duracao", DbType="Float NOT NULL")]
		public double cd_duracao
		{
			get
			{
				return this._cd_duracao;
			}
			set
			{
				if ((this._cd_duracao != value))
				{
					this.Oncd_duracaoChanging(value);
					this.SendPropertyChanging();
					this._cd_duracao = value;
					this.SendPropertyChanged("cd_duracao");
					this.Oncd_duracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_distancia", DbType="Float NOT NULL")]
		public double cd_distancia
		{
			get
			{
				return this._cd_distancia;
			}
			set
			{
				if ((this._cd_distancia != value))
				{
					this.Oncd_distanciaChanging(value);
					this.SendPropertyChanging();
					this._cd_distancia = value;
					this.SendPropertyChanged("cd_distancia");
					this.Oncd_distanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Caminho", Storage="_Cliente", ThisKey="cd_partida", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Caminho.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Caminho.Add(this);
						this._cd_partida = value.id_cliente;
					}
					else
					{
						this._cd_partida = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Caminho1", Storage="_Cliente1", ThisKey="cd_destino", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente1
		{
			get
			{
				return this._Cliente1.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente1.Entity;
				if (((previousValue != value) 
							|| (this._Cliente1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente1.Entity = null;
						previousValue.Caminho1.Remove(this);
					}
					this._Cliente1.Entity = value;
					if ((value != null))
					{
						value.Caminho1.Add(this);
						this._cd_destino = value.id_cliente;
					}
					else
					{
						this._cd_destino = default(int);
					}
					this.SendPropertyChanged("Cliente1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veiculo")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_veiculo;
		
		private int _cd_status;
		
		private string _nm_nome;
		
		private double _capacidade;
		
		private EntityRef<Tab_Tipo_Status_Veiculo> _Tab_Tipo_Status_Veiculo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_veiculoChanging(int value);
    partial void Onid_veiculoChanged();
    partial void Oncd_statusChanging(int value);
    partial void Oncd_statusChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void OncapacidadeChanging(double value);
    partial void OncapacidadeChanged();
    #endregion
		
		public Veiculo()
		{
			this._Tab_Tipo_Status_Veiculo = default(EntityRef<Tab_Tipo_Status_Veiculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_veiculo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_veiculo
		{
			get
			{
				return this._id_veiculo;
			}
			set
			{
				if ((this._id_veiculo != value))
				{
					this.Onid_veiculoChanging(value);
					this.SendPropertyChanging();
					this._id_veiculo = value;
					this.SendPropertyChanged("id_veiculo");
					this.Onid_veiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_status", DbType="Int NOT NULL")]
		public int cd_status
		{
			get
			{
				return this._cd_status;
			}
			set
			{
				if ((this._cd_status != value))
				{
					if (this._Tab_Tipo_Status_Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_statusChanging(value);
					this.SendPropertyChanging();
					this._cd_status = value;
					this.SendPropertyChanged("cd_status");
					this.Oncd_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidade", DbType="Float NOT NULL")]
		public double capacidade
		{
			get
			{
				return this._capacidade;
			}
			set
			{
				if ((this._capacidade != value))
				{
					this.OncapacidadeChanging(value);
					this.SendPropertyChanging();
					this._capacidade = value;
					this.SendPropertyChanged("capacidade");
					this.OncapacidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tipo_Status_Veiculo_Veiculo", Storage="_Tab_Tipo_Status_Veiculo", ThisKey="cd_status", OtherKey="id_status", IsForeignKey=true)]
		public Tab_Tipo_Status_Veiculo Tab_Tipo_Status_Veiculo
		{
			get
			{
				return this._Tab_Tipo_Status_Veiculo.Entity;
			}
			set
			{
				Tab_Tipo_Status_Veiculo previousValue = this._Tab_Tipo_Status_Veiculo.Entity;
				if (((previousValue != value) 
							|| (this._Tab_Tipo_Status_Veiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab_Tipo_Status_Veiculo.Entity = null;
						previousValue.Veiculo.Remove(this);
					}
					this._Tab_Tipo_Status_Veiculo.Entity = value;
					if ((value != null))
					{
						value.Veiculo.Add(this);
						this._cd_status = value.id_status;
					}
					else
					{
						this._cd_status = default(int);
					}
					this.SendPropertyChanged("Tab_Tipo_Status_Veiculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _nm_nome;
		
		private string _nm_logradouro;
		
		private string _nm_bairro;
		
		private string _nm_cep;
		
		private System.Nullable<int> _cd_numero;
		
		private string _nm_complemento;
		
		private int _cd_tipo;
		
		private string _nm_cpf_cnpj;
		
		private string _nm_cidade;
		
		private int _id_estado;
		
		private EntitySet<Caminho> _Caminho;
		
		private EntitySet<Caminho> _Caminho1;
		
		private EntitySet<Pedido> _Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Onnm_logradouroChanging(string value);
    partial void Onnm_logradouroChanged();
    partial void Onnm_bairroChanging(string value);
    partial void Onnm_bairroChanged();
    partial void Onnm_cepChanging(string value);
    partial void Onnm_cepChanged();
    partial void Oncd_numeroChanging(System.Nullable<int> value);
    partial void Oncd_numeroChanged();
    partial void Onnm_complementoChanging(string value);
    partial void Onnm_complementoChanged();
    partial void Oncd_tipoChanging(int value);
    partial void Oncd_tipoChanged();
    partial void Onnm_cpf_cnpjChanging(string value);
    partial void Onnm_cpf_cnpjChanged();
    partial void Onnm_cidadeChanging(string value);
    partial void Onnm_cidadeChanged();
    partial void Onid_estadoChanging(int value);
    partial void Onid_estadoChanged();
    #endregion
		
		public Cliente()
		{
			this._Caminho = new EntitySet<Caminho>(new Action<Caminho>(this.attach_Caminho), new Action<Caminho>(this.detach_Caminho));
			this._Caminho1 = new EntitySet<Caminho>(new Action<Caminho>(this.attach_Caminho1), new Action<Caminho>(this.detach_Caminho1));
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_logradouro", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nm_logradouro
		{
			get
			{
				return this._nm_logradouro;
			}
			set
			{
				if ((this._nm_logradouro != value))
				{
					this.Onnm_logradouroChanging(value);
					this.SendPropertyChanging();
					this._nm_logradouro = value;
					this.SendPropertyChanged("nm_logradouro");
					this.Onnm_logradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_bairro
		{
			get
			{
				return this._nm_bairro;
			}
			set
			{
				if ((this._nm_bairro != value))
				{
					this.Onnm_bairroChanging(value);
					this.SendPropertyChanging();
					this._nm_bairro = value;
					this.SendPropertyChanged("nm_bairro");
					this.Onnm_bairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cep", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string nm_cep
		{
			get
			{
				return this._nm_cep;
			}
			set
			{
				if ((this._nm_cep != value))
				{
					this.Onnm_cepChanging(value);
					this.SendPropertyChanging();
					this._nm_cep = value;
					this.SendPropertyChanged("nm_cep");
					this.Onnm_cepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_numero", DbType="Int")]
		public System.Nullable<int> cd_numero
		{
			get
			{
				return this._cd_numero;
			}
			set
			{
				if ((this._cd_numero != value))
				{
					this.Oncd_numeroChanging(value);
					this.SendPropertyChanging();
					this._cd_numero = value;
					this.SendPropertyChanged("cd_numero");
					this.Oncd_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_complemento", DbType="VarChar(50)")]
		public string nm_complemento
		{
			get
			{
				return this._nm_complemento;
			}
			set
			{
				if ((this._nm_complemento != value))
				{
					this.Onnm_complementoChanging(value);
					this.SendPropertyChanging();
					this._nm_complemento = value;
					this.SendPropertyChanged("nm_complemento");
					this.Onnm_complementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_tipo", DbType="Int NOT NULL")]
		public int cd_tipo
		{
			get
			{
				return this._cd_tipo;
			}
			set
			{
				if ((this._cd_tipo != value))
				{
					this.Oncd_tipoChanging(value);
					this.SendPropertyChanging();
					this._cd_tipo = value;
					this.SendPropertyChanged("cd_tipo");
					this.Oncd_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cpf_cnpj", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nm_cpf_cnpj
		{
			get
			{
				return this._nm_cpf_cnpj;
			}
			set
			{
				if ((this._nm_cpf_cnpj != value))
				{
					this.Onnm_cpf_cnpjChanging(value);
					this.SendPropertyChanging();
					this._nm_cpf_cnpj = value;
					this.SendPropertyChanged("nm_cpf_cnpj");
					this.Onnm_cpf_cnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_cidade
		{
			get
			{
				return this._nm_cidade;
			}
			set
			{
				if ((this._nm_cidade != value))
				{
					this.Onnm_cidadeChanging(value);
					this.SendPropertyChanging();
					this._nm_cidade = value;
					this.SendPropertyChanged("nm_cidade");
					this.Onnm_cidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int NOT NULL")]
		public int id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					this.Onid_estadoChanging(value);
					this.SendPropertyChanging();
					this._id_estado = value;
					this.SendPropertyChanged("id_estado");
					this.Onid_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Caminho", Storage="_Caminho", ThisKey="id_cliente", OtherKey="cd_partida")]
		public EntitySet<Caminho> Caminho
		{
			get
			{
				return this._Caminho;
			}
			set
			{
				this._Caminho.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Caminho1", Storage="_Caminho1", ThisKey="id_cliente", OtherKey="cd_destino")]
		public EntitySet<Caminho> Caminho1
		{
			get
			{
				return this._Caminho1;
			}
			set
			{
				this._Caminho1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Pedido", ThisKey="id_cliente", OtherKey="cd_cliente")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Caminho(Caminho entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Caminho(Caminho entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Caminho1(Caminho entity)
		{
			this.SendPropertyChanging();
			entity.Cliente1 = this;
		}
		
		private void detach_Caminho1(Caminho entity)
		{
			this.SendPropertyChanging();
			entity.Cliente1 = null;
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demanda")]
	public partial class Demanda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_demanda;
		
		private int _cd_pedido;
		
		private int _cd_produto;
		
		private int _qtd_produto;
		
		private EntityRef<Pedido> _Pedido;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_demandaChanging(int value);
    partial void Onid_demandaChanged();
    partial void Oncd_pedidoChanging(int value);
    partial void Oncd_pedidoChanged();
    partial void Oncd_produtoChanging(int value);
    partial void Oncd_produtoChanged();
    partial void Onqtd_produtoChanging(int value);
    partial void Onqtd_produtoChanged();
    #endregion
		
		public Demanda()
		{
			this._Pedido = default(EntityRef<Pedido>);
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_demanda", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_demanda
		{
			get
			{
				return this._id_demanda;
			}
			set
			{
				if ((this._id_demanda != value))
				{
					this.Onid_demandaChanging(value);
					this.SendPropertyChanging();
					this._id_demanda = value;
					this.SendPropertyChanged("id_demanda");
					this.Onid_demandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_pedido", DbType="Int NOT NULL")]
		public int cd_pedido
		{
			get
			{
				return this._cd_pedido;
			}
			set
			{
				if ((this._cd_pedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_pedidoChanging(value);
					this.SendPropertyChanging();
					this._cd_pedido = value;
					this.SendPropertyChanged("cd_pedido");
					this.Oncd_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_produto", DbType="Int NOT NULL")]
		public int cd_produto
		{
			get
			{
				return this._cd_produto;
			}
			set
			{
				if ((this._cd_produto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_produtoChanging(value);
					this.SendPropertyChanging();
					this._cd_produto = value;
					this.SendPropertyChanged("cd_produto");
					this.Oncd_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtd_produto", DbType="Int NOT NULL")]
		public int qtd_produto
		{
			get
			{
				return this._qtd_produto;
			}
			set
			{
				if ((this._qtd_produto != value))
				{
					this.Onqtd_produtoChanging(value);
					this.SendPropertyChanging();
					this._qtd_produto = value;
					this.SendPropertyChanged("qtd_produto");
					this.Onqtd_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Demanda", Storage="_Pedido", ThisKey="cd_pedido", OtherKey="id_pedido", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Demanda.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Demanda.Add(this);
						this._cd_pedido = value.id_pedido;
					}
					else
					{
						this._cd_pedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Demanda", Storage="_Produto", ThisKey="cd_produto", OtherKey="id_produto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Demanda.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Demanda.Add(this);
						this._cd_produto = value.id_produto;
					}
					else
					{
						this._cd_produto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pedido;
		
		private int _cd_cliente;
		
		private int _cd_status;
		
		private EntitySet<Demanda> _Demanda;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Tab_Tipo_Status> _Tab_Tipo_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Oncd_clienteChanging(int value);
    partial void Oncd_clienteChanged();
    partial void Oncd_statusChanging(int value);
    partial void Oncd_statusChanged();
    #endregion
		
		public Pedido()
		{
			this._Demanda = new EntitySet<Demanda>(new Action<Demanda>(this.attach_Demanda), new Action<Demanda>(this.detach_Demanda));
			this._Cliente = default(EntityRef<Cliente>);
			this._Tab_Tipo_Status = default(EntityRef<Tab_Tipo_Status>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_cliente", DbType="Int NOT NULL")]
		public int cd_cliente
		{
			get
			{
				return this._cd_cliente;
			}
			set
			{
				if ((this._cd_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_clienteChanging(value);
					this.SendPropertyChanging();
					this._cd_cliente = value;
					this.SendPropertyChanged("cd_cliente");
					this.Oncd_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_status", DbType="Int NOT NULL")]
		public int cd_status
		{
			get
			{
				return this._cd_status;
			}
			set
			{
				if ((this._cd_status != value))
				{
					if (this._Tab_Tipo_Status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_statusChanging(value);
					this.SendPropertyChanging();
					this._cd_status = value;
					this.SendPropertyChanged("cd_status");
					this.Oncd_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Demanda", Storage="_Demanda", ThisKey="id_pedido", OtherKey="cd_pedido")]
		public EntitySet<Demanda> Demanda
		{
			get
			{
				return this._Demanda;
			}
			set
			{
				this._Demanda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Cliente", ThisKey="cd_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._cd_cliente = value.id_cliente;
					}
					else
					{
						this._cd_cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tipo_Status_Pedido", Storage="_Tab_Tipo_Status", ThisKey="cd_status", OtherKey="id_status", IsForeignKey=true)]
		public Tab_Tipo_Status Tab_Tipo_Status
		{
			get
			{
				return this._Tab_Tipo_Status.Entity;
			}
			set
			{
				Tab_Tipo_Status previousValue = this._Tab_Tipo_Status.Entity;
				if (((previousValue != value) 
							|| (this._Tab_Tipo_Status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab_Tipo_Status.Entity = null;
						previousValue.Pedido.Remove(this);
					}
					this._Tab_Tipo_Status.Entity = value;
					if ((value != null))
					{
						value.Pedido.Add(this);
						this._cd_status = value.id_status;
					}
					else
					{
						this._cd_status = default(int);
					}
					this.SendPropertyChanged("Tab_Tipo_Status");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Demanda(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Demanda(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _nm_nome;
		
		private int _cd_duracao_descarga;
		
		private int _cd_espaco_ocupado;
		
		private string _nm_descricao;
		
		private EntitySet<Demanda> _Demanda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Oncd_duracao_descargaChanging(int value);
    partial void Oncd_duracao_descargaChanged();
    partial void Oncd_espaco_ocupadoChanging(int value);
    partial void Oncd_espaco_ocupadoChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Produto()
		{
			this._Demanda = new EntitySet<Demanda>(new Action<Demanda>(this.attach_Demanda), new Action<Demanda>(this.detach_Demanda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_duracao_descarga", DbType="Int NOT NULL")]
		public int cd_duracao_descarga
		{
			get
			{
				return this._cd_duracao_descarga;
			}
			set
			{
				if ((this._cd_duracao_descarga != value))
				{
					this.Oncd_duracao_descargaChanging(value);
					this.SendPropertyChanging();
					this._cd_duracao_descarga = value;
					this.SendPropertyChanged("cd_duracao_descarga");
					this.Oncd_duracao_descargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_espaco_ocupado", DbType="Int NOT NULL")]
		public int cd_espaco_ocupado
		{
			get
			{
				return this._cd_espaco_ocupado;
			}
			set
			{
				if ((this._cd_espaco_ocupado != value))
				{
					this.Oncd_espaco_ocupadoChanging(value);
					this.SendPropertyChanging();
					this._cd_espaco_ocupado = value;
					this.SendPropertyChanged("cd_espaco_ocupado");
					this.Oncd_espaco_ocupadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(100)")]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Demanda", Storage="_Demanda", ThisKey="id_produto", OtherKey="cd_produto")]
		public EntitySet<Demanda> Demanda
		{
			get
			{
				return this._Demanda;
			}
			set
			{
				this._Demanda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Demanda(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Demanda(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tab_Tipo_Status")]
	public partial class Tab_Tipo_Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _nm_descricao;
		
		private EntitySet<Pedido> _Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Tab_Tipo_Status()
		{
			this._Pedido = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedido), new Action<Pedido>(this.detach_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tipo_Status_Pedido", Storage="_Pedido", ThisKey="id_status", OtherKey="cd_status")]
		public EntitySet<Pedido> Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				this._Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Tipo_Status = this;
		}
		
		private void detach_Pedido(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Tipo_Status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tab_Tipo_Status_Veiculo")]
	public partial class Tab_Tipo_Status_Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _nm_descricao;
		
		private EntitySet<Veiculo> _Veiculo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Tab_Tipo_Status_Veiculo()
		{
			this._Veiculo = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculo), new Action<Veiculo>(this.detach_Veiculo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tipo_Status_Veiculo_Veiculo", Storage="_Veiculo", ThisKey="id_status", OtherKey="cd_status")]
		public EntitySet<Veiculo> Veiculo
		{
			get
			{
				return this._Veiculo;
			}
			set
			{
				this._Veiculo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Veiculo(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Tipo_Status_Veiculo = this;
		}
		
		private void detach_Veiculo(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Tipo_Status_Veiculo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nm_cpf;
		
		private string _nm_nome;
		
		private string _nm_login;
		
		private string _nm_senha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnm_cpfChanging(string value);
    partial void Onnm_cpfChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Onnm_loginChanging(string value);
    partial void Onnm_loginChanged();
    partial void Onnm_senhaChanging(string value);
    partial void Onnm_senhaChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cpf", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string nm_cpf
		{
			get
			{
				return this._nm_cpf;
			}
			set
			{
				if ((this._nm_cpf != value))
				{
					this.Onnm_cpfChanging(value);
					this.SendPropertyChanging();
					this._nm_cpf = value;
					this.SendPropertyChanged("nm_cpf");
					this.Onnm_cpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_login", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nm_login
		{
			get
			{
				return this._nm_login;
			}
			set
			{
				if ((this._nm_login != value))
				{
					this.Onnm_loginChanging(value);
					this.SendPropertyChanging();
					this._nm_login = value;
					this.SendPropertyChanged("nm_login");
					this.Onnm_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_senha", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nm_senha
		{
			get
			{
				return this._nm_senha;
			}
			set
			{
				if ((this._nm_senha != value))
				{
					this.Onnm_senhaChanging(value);
					this.SendPropertyChanging();
					this._nm_senha = value;
					this.SendPropertyChanged("nm_senha");
					this.Onnm_senhaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
