#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTRE.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOTRE")]
	public partial class SOTREDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertViagem(Viagem instance);
    partial void UpdateViagem(Viagem instance);
    partial void DeleteViagem(Viagem instance);
    partial void InsertDemanda(Demanda instance);
    partial void UpdateDemanda(Demanda instance);
    partial void DeleteDemanda(Demanda instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertStatus_Pedido(Status_Pedido instance);
    partial void UpdateStatus_Pedido(Status_Pedido instance);
    partial void DeleteStatus_Pedido(Status_Pedido instance);
    partial void InsertStatus_Veiculo(Status_Veiculo instance);
    partial void UpdateStatus_Veiculo(Status_Veiculo instance);
    partial void DeleteStatus_Veiculo(Status_Veiculo instance);
    partial void InsertTipo_Cliente(Tipo_Cliente instance);
    partial void UpdateTipo_Cliente(Tipo_Cliente instance);
    partial void DeleteTipo_Cliente(Tipo_Cliente instance);
    partial void InsertTurno(Turno instance);
    partial void UpdateTurno(Turno instance);
    partial void DeleteTurno(Turno instance);
    partial void InsertTurno_Cliente(Turno_Cliente instance);
    partial void UpdateTurno_Cliente(Turno_Cliente instance);
    partial void DeleteTurno_Cliente(Turno_Cliente instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    #endregion
		
		public SOTREDataContext() : 
				base(global::SOTRE.Domain.Properties.Settings.Default.SOTREConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SOTREDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Viagem> Viagems
		{
			get
			{
				return this.GetTable<Viagem>();
			}
		}
		
		public System.Data.Linq.Table<Demanda> Demandas
		{
			get
			{
				return this.GetTable<Demanda>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Status_Pedido> Status_Pedidos
		{
			get
			{
				return this.GetTable<Status_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Status_Veiculo> Status_Veiculos
		{
			get
			{
				return this.GetTable<Status_Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Cliente> Tipo_Clientes
		{
			get
			{
				return this.GetTable<Tipo_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Turno> Turnos
		{
			get
			{
				return this.GetTable<Turno>();
			}
		}
		
		public System.Data.Linq.Table<Turno_Cliente> Turno_Clientes
		{
			get
			{
				return this.GetTable<Turno_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculos
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _nm_nome;
		
		private string _nm_logradouro;
		
		private string _nm_bairro;
		
		private string _nm_cep;
		
		private System.Nullable<int> _cd_numero;
		
		private string _nm_complemento;
		
		private int _cd_tipo;
		
		private string _nm_cpf_cnpj;
		
		private string _nm_cidade;
		
		private string _nm_longitude;
		
		private string _nm_latitude;
		
		private EntitySet<Viagem> _Viagems;
		
		private EntitySet<Viagem> _Viagems1;
		
		private EntitySet<Pedido> _Pedidos;
		
		private EntitySet<Turno_Cliente> _Turno_Clientes;
		
		private EntityRef<Tipo_Cliente> _Tipo_Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Onnm_logradouroChanging(string value);
    partial void Onnm_logradouroChanged();
    partial void Onnm_bairroChanging(string value);
    partial void Onnm_bairroChanged();
    partial void Onnm_cepChanging(string value);
    partial void Onnm_cepChanged();
    partial void Oncd_numeroChanging(System.Nullable<int> value);
    partial void Oncd_numeroChanged();
    partial void Onnm_complementoChanging(string value);
    partial void Onnm_complementoChanged();
    partial void Oncd_tipoChanging(int value);
    partial void Oncd_tipoChanged();
    partial void Onnm_cpf_cnpjChanging(string value);
    partial void Onnm_cpf_cnpjChanged();
    partial void Onnm_cidadeChanging(string value);
    partial void Onnm_cidadeChanged();
    partial void Onnm_longitudeChanging(string value);
    partial void Onnm_longitudeChanged();
    partial void Onnm_latitudeChanging(string value);
    partial void Onnm_latitudeChanged();
    #endregion
		
		public Cliente()
		{
			this._Viagems = new EntitySet<Viagem>(new Action<Viagem>(this.attach_Viagems), new Action<Viagem>(this.detach_Viagems));
			this._Viagems1 = new EntitySet<Viagem>(new Action<Viagem>(this.attach_Viagems1), new Action<Viagem>(this.detach_Viagems1));
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			this._Turno_Clientes = new EntitySet<Turno_Cliente>(new Action<Turno_Cliente>(this.attach_Turno_Clientes), new Action<Turno_Cliente>(this.detach_Turno_Clientes));
			this._Tipo_Cliente = default(EntityRef<Tipo_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_logradouro", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nm_logradouro
		{
			get
			{
				return this._nm_logradouro;
			}
			set
			{
				if ((this._nm_logradouro != value))
				{
					this.Onnm_logradouroChanging(value);
					this.SendPropertyChanging();
					this._nm_logradouro = value;
					this.SendPropertyChanged("nm_logradouro");
					this.Onnm_logradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_bairro
		{
			get
			{
				return this._nm_bairro;
			}
			set
			{
				if ((this._nm_bairro != value))
				{
					this.Onnm_bairroChanging(value);
					this.SendPropertyChanging();
					this._nm_bairro = value;
					this.SendPropertyChanged("nm_bairro");
					this.Onnm_bairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cep", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string nm_cep
		{
			get
			{
				return this._nm_cep;
			}
			set
			{
				if ((this._nm_cep != value))
				{
					this.Onnm_cepChanging(value);
					this.SendPropertyChanging();
					this._nm_cep = value;
					this.SendPropertyChanged("nm_cep");
					this.Onnm_cepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_numero", DbType="Int")]
		public System.Nullable<int> cd_numero
		{
			get
			{
				return this._cd_numero;
			}
			set
			{
				if ((this._cd_numero != value))
				{
					this.Oncd_numeroChanging(value);
					this.SendPropertyChanging();
					this._cd_numero = value;
					this.SendPropertyChanged("cd_numero");
					this.Oncd_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_complemento", DbType="VarChar(50)")]
		public string nm_complemento
		{
			get
			{
				return this._nm_complemento;
			}
			set
			{
				if ((this._nm_complemento != value))
				{
					this.Onnm_complementoChanging(value);
					this.SendPropertyChanging();
					this._nm_complemento = value;
					this.SendPropertyChanged("nm_complemento");
					this.Onnm_complementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_tipo", DbType="Int NOT NULL")]
		public int cd_tipo
		{
			get
			{
				return this._cd_tipo;
			}
			set
			{
				if ((this._cd_tipo != value))
				{
					if (this._Tipo_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_tipoChanging(value);
					this.SendPropertyChanging();
					this._cd_tipo = value;
					this.SendPropertyChanged("cd_tipo");
					this.Oncd_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cpf_cnpj", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nm_cpf_cnpj
		{
			get
			{
				return this._nm_cpf_cnpj;
			}
			set
			{
				if ((this._nm_cpf_cnpj != value))
				{
					this.Onnm_cpf_cnpjChanging(value);
					this.SendPropertyChanging();
					this._nm_cpf_cnpj = value;
					this.SendPropertyChanged("nm_cpf_cnpj");
					this.Onnm_cpf_cnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_cidade
		{
			get
			{
				return this._nm_cidade;
			}
			set
			{
				if ((this._nm_cidade != value))
				{
					this.Onnm_cidadeChanging(value);
					this.SendPropertyChanging();
					this._nm_cidade = value;
					this.SendPropertyChanged("nm_cidade");
					this.Onnm_cidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_longitude", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nm_longitude
		{
			get
			{
				return this._nm_longitude;
			}
			set
			{
				if ((this._nm_longitude != value))
				{
					this.Onnm_longitudeChanging(value);
					this.SendPropertyChanging();
					this._nm_longitude = value;
					this.SendPropertyChanged("nm_longitude");
					this.Onnm_longitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_latitude", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nm_latitude
		{
			get
			{
				return this._nm_latitude;
			}
			set
			{
				if ((this._nm_latitude != value))
				{
					this.Onnm_latitudeChanging(value);
					this.SendPropertyChanging();
					this._nm_latitude = value;
					this.SendPropertyChanged("nm_latitude");
					this.Onnm_latitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Viagem", Storage="_Viagems", ThisKey="id_cliente", OtherKey="cd_partida")]
		public EntitySet<Viagem> Viagems
		{
			get
			{
				return this._Viagems;
			}
			set
			{
				this._Viagems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Viagem1", Storage="_Viagems1", ThisKey="id_cliente", OtherKey="cd_destino")]
		public EntitySet<Viagem> Viagems1
		{
			get
			{
				return this._Viagems1;
			}
			set
			{
				this._Viagems1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Pedidos", ThisKey="id_cliente", OtherKey="cd_cliente")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Turno_Cliente", Storage="_Turno_Clientes", ThisKey="id_cliente", OtherKey="cd_cliente")]
		public EntitySet<Turno_Cliente> Turno_Clientes
		{
			get
			{
				return this._Turno_Clientes;
			}
			set
			{
				this._Turno_Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Cliente_Cliente", Storage="_Tipo_Cliente", ThisKey="cd_tipo", OtherKey="id_tipo", IsForeignKey=true)]
		public Tipo_Cliente Tipo_Cliente
		{
			get
			{
				return this._Tipo_Cliente.Entity;
			}
			set
			{
				Tipo_Cliente previousValue = this._Tipo_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_Cliente.Entity = null;
						previousValue.Clientes.Remove(this);
					}
					this._Tipo_Cliente.Entity = value;
					if ((value != null))
					{
						value.Clientes.Add(this);
						this._cd_tipo = value.id_tipo;
					}
					else
					{
						this._cd_tipo = default(int);
					}
					this.SendPropertyChanged("Tipo_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Viagems(Viagem entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Viagems(Viagem entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Viagems1(Viagem entity)
		{
			this.SendPropertyChanging();
			entity.Cliente1 = this;
		}
		
		private void detach_Viagems1(Viagem entity)
		{
			this.SendPropertyChanging();
			entity.Cliente1 = null;
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Turno_Clientes(Turno_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Turno_Clientes(Turno_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viagem")]
	public partial class Viagem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_caminho;
		
		private int _cd_partida;
		
		private int _cd_destino;
		
		private double _cd_duracao;
		
		private double _cd_distancia;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Cliente> _Cliente1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_caminhoChanging(int value);
    partial void Onid_caminhoChanged();
    partial void Oncd_partidaChanging(int value);
    partial void Oncd_partidaChanged();
    partial void Oncd_destinoChanging(int value);
    partial void Oncd_destinoChanged();
    partial void Oncd_duracaoChanging(double value);
    partial void Oncd_duracaoChanged();
    partial void Oncd_distanciaChanging(double value);
    partial void Oncd_distanciaChanged();
    #endregion
		
		public Viagem()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Cliente1 = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_caminho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_caminho
		{
			get
			{
				return this._id_caminho;
			}
			set
			{
				if ((this._id_caminho != value))
				{
					this.Onid_caminhoChanging(value);
					this.SendPropertyChanging();
					this._id_caminho = value;
					this.SendPropertyChanged("id_caminho");
					this.Onid_caminhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_partida", DbType="Int NOT NULL")]
		public int cd_partida
		{
			get
			{
				return this._cd_partida;
			}
			set
			{
				if ((this._cd_partida != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_partidaChanging(value);
					this.SendPropertyChanging();
					this._cd_partida = value;
					this.SendPropertyChanged("cd_partida");
					this.Oncd_partidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_destino", DbType="Int NOT NULL")]
		public int cd_destino
		{
			get
			{
				return this._cd_destino;
			}
			set
			{
				if ((this._cd_destino != value))
				{
					if (this._Cliente1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_destinoChanging(value);
					this.SendPropertyChanging();
					this._cd_destino = value;
					this.SendPropertyChanged("cd_destino");
					this.Oncd_destinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_duracao", DbType="Float NOT NULL")]
		public double cd_duracao
		{
			get
			{
				return this._cd_duracao;
			}
			set
			{
				if ((this._cd_duracao != value))
				{
					this.Oncd_duracaoChanging(value);
					this.SendPropertyChanging();
					this._cd_duracao = value;
					this.SendPropertyChanged("cd_duracao");
					this.Oncd_duracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_distancia", DbType="Float NOT NULL")]
		public double cd_distancia
		{
			get
			{
				return this._cd_distancia;
			}
			set
			{
				if ((this._cd_distancia != value))
				{
					this.Oncd_distanciaChanging(value);
					this.SendPropertyChanging();
					this._cd_distancia = value;
					this.SendPropertyChanged("cd_distancia");
					this.Oncd_distanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Viagem", Storage="_Cliente", ThisKey="cd_partida", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Viagems.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Viagems.Add(this);
						this._cd_partida = value.id_cliente;
					}
					else
					{
						this._cd_partida = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Viagem1", Storage="_Cliente1", ThisKey="cd_destino", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente1
		{
			get
			{
				return this._Cliente1.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente1.Entity;
				if (((previousValue != value) 
							|| (this._Cliente1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente1.Entity = null;
						previousValue.Viagems1.Remove(this);
					}
					this._Cliente1.Entity = value;
					if ((value != null))
					{
						value.Viagems1.Add(this);
						this._cd_destino = value.id_cliente;
					}
					else
					{
						this._cd_destino = default(int);
					}
					this.SendPropertyChanged("Cliente1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Demanda")]
	public partial class Demanda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_demanda;
		
		private int _cd_pedido;
		
		private int _cd_produto;
		
		private int _qtd_produto;
		
		private EntityRef<Pedido> _Pedido;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_demandaChanging(int value);
    partial void Onid_demandaChanged();
    partial void Oncd_pedidoChanging(int value);
    partial void Oncd_pedidoChanged();
    partial void Oncd_produtoChanging(int value);
    partial void Oncd_produtoChanged();
    partial void Onqtd_produtoChanging(int value);
    partial void Onqtd_produtoChanged();
    #endregion
		
		public Demanda()
		{
			this._Pedido = default(EntityRef<Pedido>);
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_demanda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_demanda
		{
			get
			{
				return this._id_demanda;
			}
			set
			{
				if ((this._id_demanda != value))
				{
					this.Onid_demandaChanging(value);
					this.SendPropertyChanging();
					this._id_demanda = value;
					this.SendPropertyChanged("id_demanda");
					this.Onid_demandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_pedido", DbType="Int NOT NULL")]
		public int cd_pedido
		{
			get
			{
				return this._cd_pedido;
			}
			set
			{
				if ((this._cd_pedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_pedidoChanging(value);
					this.SendPropertyChanging();
					this._cd_pedido = value;
					this.SendPropertyChanged("cd_pedido");
					this.Oncd_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_produto", DbType="Int NOT NULL")]
		public int cd_produto
		{
			get
			{
				return this._cd_produto;
			}
			set
			{
				if ((this._cd_produto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_produtoChanging(value);
					this.SendPropertyChanging();
					this._cd_produto = value;
					this.SendPropertyChanged("cd_produto");
					this.Oncd_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtd_produto", DbType="Int NOT NULL")]
		public int qtd_produto
		{
			get
			{
				return this._qtd_produto;
			}
			set
			{
				if ((this._qtd_produto != value))
				{
					this.Onqtd_produtoChanging(value);
					this.SendPropertyChanging();
					this._qtd_produto = value;
					this.SendPropertyChanged("qtd_produto");
					this.Onqtd_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Demanda", Storage="_Pedido", ThisKey="cd_pedido", OtherKey="id_pedido", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Demandas.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Demandas.Add(this);
						this._cd_pedido = value.id_pedido;
					}
					else
					{
						this._cd_pedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Demanda", Storage="_Produto", ThisKey="cd_produto", OtherKey="id_produto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Demandas.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Demandas.Add(this);
						this._cd_produto = value.id_produto;
					}
					else
					{
						this._cd_produto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pedido;
		
		private int _cd_cliente;
		
		private int _cd_status;
		
		private EntitySet<Demanda> _Demandas;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Status_Pedido> _Status_Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void Oncd_clienteChanging(int value);
    partial void Oncd_clienteChanged();
    partial void Oncd_statusChanging(int value);
    partial void Oncd_statusChanged();
    #endregion
		
		public Pedido()
		{
			this._Demandas = new EntitySet<Demanda>(new Action<Demanda>(this.attach_Demandas), new Action<Demanda>(this.detach_Demandas));
			this._Cliente = default(EntityRef<Cliente>);
			this._Status_Pedido = default(EntityRef<Status_Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_cliente", DbType="Int NOT NULL")]
		public int cd_cliente
		{
			get
			{
				return this._cd_cliente;
			}
			set
			{
				if ((this._cd_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_clienteChanging(value);
					this.SendPropertyChanging();
					this._cd_cliente = value;
					this.SendPropertyChanged("cd_cliente");
					this.Oncd_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_status", DbType="Int NOT NULL")]
		public int cd_status
		{
			get
			{
				return this._cd_status;
			}
			set
			{
				if ((this._cd_status != value))
				{
					if (this._Status_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_statusChanging(value);
					this.SendPropertyChanging();
					this._cd_status = value;
					this.SendPropertyChanged("cd_status");
					this.Oncd_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Demanda", Storage="_Demandas", ThisKey="id_pedido", OtherKey="cd_pedido")]
		public EntitySet<Demanda> Demandas
		{
			get
			{
				return this._Demandas;
			}
			set
			{
				this._Demandas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Cliente", ThisKey="cd_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._cd_cliente = value.id_cliente;
					}
					else
					{
						this._cd_cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Pedido_Pedido", Storage="_Status_Pedido", ThisKey="cd_status", OtherKey="id_status", IsForeignKey=true)]
		public Status_Pedido Status_Pedido
		{
			get
			{
				return this._Status_Pedido.Entity;
			}
			set
			{
				Status_Pedido previousValue = this._Status_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Status_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Status_Pedido.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Status_Pedido.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._cd_status = value.id_status;
					}
					else
					{
						this._cd_status = default(int);
					}
					this.SendPropertyChanged("Status_Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Demandas(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Demandas(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _nm_nome;
		
		private int _cd_duracao_descarga;
		
		private int _cd_espaco_ocupado;
		
		private string _nm_descricao;
		
		private EntitySet<Demanda> _Demandas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Oncd_duracao_descargaChanging(int value);
    partial void Oncd_duracao_descargaChanged();
    partial void Oncd_espaco_ocupadoChanging(int value);
    partial void Oncd_espaco_ocupadoChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Produto()
		{
			this._Demandas = new EntitySet<Demanda>(new Action<Demanda>(this.attach_Demandas), new Action<Demanda>(this.detach_Demandas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_duracao_descarga", DbType="Int NOT NULL")]
		public int cd_duracao_descarga
		{
			get
			{
				return this._cd_duracao_descarga;
			}
			set
			{
				if ((this._cd_duracao_descarga != value))
				{
					this.Oncd_duracao_descargaChanging(value);
					this.SendPropertyChanging();
					this._cd_duracao_descarga = value;
					this.SendPropertyChanged("cd_duracao_descarga");
					this.Oncd_duracao_descargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_espaco_ocupado", DbType="Int NOT NULL")]
		public int cd_espaco_ocupado
		{
			get
			{
				return this._cd_espaco_ocupado;
			}
			set
			{
				if ((this._cd_espaco_ocupado != value))
				{
					this.Oncd_espaco_ocupadoChanging(value);
					this.SendPropertyChanging();
					this._cd_espaco_ocupado = value;
					this.SendPropertyChanged("cd_espaco_ocupado");
					this.Oncd_espaco_ocupadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(100)")]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Demanda", Storage="_Demandas", ThisKey="id_produto", OtherKey="cd_produto")]
		public EntitySet<Demanda> Demandas
		{
			get
			{
				return this._Demandas;
			}
			set
			{
				this._Demandas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Demandas(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Demandas(Demanda entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status_Pedido")]
	public partial class Status_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _nm_descricao;
		
		private EntitySet<Pedido> _Pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Status_Pedido()
		{
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Pedido_Pedido", Storage="_Pedidos", ThisKey="id_status", OtherKey="cd_status")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Status_Pedido = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Status_Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status_Veiculo")]
	public partial class Status_Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _nm_descricao;
		
		private EntitySet<Veiculo> _Veiculos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Status_Veiculo()
		{
			this._Veiculos = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculos), new Action<Veiculo>(this.detach_Veiculos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Veiculo_Veiculo", Storage="_Veiculos", ThisKey="id_status", OtherKey="cd_status")]
		public EntitySet<Veiculo> Veiculos
		{
			get
			{
				return this._Veiculos;
			}
			set
			{
				this._Veiculos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Status_Veiculo = this;
		}
		
		private void detach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Status_Veiculo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Cliente")]
	public partial class Tipo_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo;
		
		private string _nm_descricao;
		
		private EntitySet<Cliente> _Clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoChanging(int value);
    partial void Onid_tipoChanged();
    partial void Onnm_descricaoChanging(string value);
    partial void Onnm_descricaoChanged();
    #endregion
		
		public Tipo_Cliente()
		{
			this._Clientes = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Clientes), new Action<Cliente>(this.detach_Clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo
		{
			get
			{
				return this._id_tipo;
			}
			set
			{
				if ((this._id_tipo != value))
				{
					this.Onid_tipoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo = value;
					this.SendPropertyChanged("id_tipo");
					this.Onid_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_descricao", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nm_descricao
		{
			get
			{
				return this._nm_descricao;
			}
			set
			{
				if ((this._nm_descricao != value))
				{
					this.Onnm_descricaoChanging(value);
					this.SendPropertyChanging();
					this._nm_descricao = value;
					this.SendPropertyChanged("nm_descricao");
					this.Onnm_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Cliente_Cliente", Storage="_Clientes", ThisKey="id_tipo", OtherKey="cd_tipo")]
		public EntitySet<Cliente> Clientes
		{
			get
			{
				return this._Clientes;
			}
			set
			{
				this._Clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Cliente = this;
		}
		
		private void detach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turno")]
	public partial class Turno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_turno;
		
		private int _cd_horaInicial;
		
		private int _cd_horaFinal;
		
		private int _cd_trafego;
		
		private EntitySet<Turno_Cliente> _Turno_Clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_turnoChanging(int value);
    partial void Onid_turnoChanged();
    partial void Oncd_horaInicialChanging(int value);
    partial void Oncd_horaInicialChanged();
    partial void Oncd_horaFinalChanging(int value);
    partial void Oncd_horaFinalChanged();
    partial void Oncd_trafegoChanging(int value);
    partial void Oncd_trafegoChanged();
    #endregion
		
		public Turno()
		{
			this._Turno_Clientes = new EntitySet<Turno_Cliente>(new Action<Turno_Cliente>(this.attach_Turno_Clientes), new Action<Turno_Cliente>(this.detach_Turno_Clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_turno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_turno
		{
			get
			{
				return this._id_turno;
			}
			set
			{
				if ((this._id_turno != value))
				{
					this.Onid_turnoChanging(value);
					this.SendPropertyChanging();
					this._id_turno = value;
					this.SendPropertyChanged("id_turno");
					this.Onid_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_horaInicial", DbType="Int NOT NULL")]
		public int cd_horaInicial
		{
			get
			{
				return this._cd_horaInicial;
			}
			set
			{
				if ((this._cd_horaInicial != value))
				{
					this.Oncd_horaInicialChanging(value);
					this.SendPropertyChanging();
					this._cd_horaInicial = value;
					this.SendPropertyChanged("cd_horaInicial");
					this.Oncd_horaInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_horaFinal", DbType="Int NOT NULL")]
		public int cd_horaFinal
		{
			get
			{
				return this._cd_horaFinal;
			}
			set
			{
				if ((this._cd_horaFinal != value))
				{
					this.Oncd_horaFinalChanging(value);
					this.SendPropertyChanging();
					this._cd_horaFinal = value;
					this.SendPropertyChanged("cd_horaFinal");
					this.Oncd_horaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_trafego", DbType="Int NOT NULL")]
		public int cd_trafego
		{
			get
			{
				return this._cd_trafego;
			}
			set
			{
				if ((this._cd_trafego != value))
				{
					this.Oncd_trafegoChanging(value);
					this.SendPropertyChanging();
					this._cd_trafego = value;
					this.SendPropertyChanged("cd_trafego");
					this.Oncd_trafegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turno_Turno_Cliente", Storage="_Turno_Clientes", ThisKey="id_turno", OtherKey="cd_turno")]
		public EntitySet<Turno_Cliente> Turno_Clientes
		{
			get
			{
				return this._Turno_Clientes;
			}
			set
			{
				this._Turno_Clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Turno_Clientes(Turno_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Turno = this;
		}
		
		private void detach_Turno_Clientes(Turno_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Turno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turno_Cliente")]
	public partial class Turno_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_turno_cliente;
		
		private int _cd_cliente;
		
		private int _cd_turno;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Turno> _Turno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_turno_clienteChanging(int value);
    partial void Onid_turno_clienteChanged();
    partial void Oncd_clienteChanging(int value);
    partial void Oncd_clienteChanged();
    partial void Oncd_turnoChanging(int value);
    partial void Oncd_turnoChanged();
    #endregion
		
		public Turno_Cliente()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Turno = default(EntityRef<Turno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_turno_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_turno_cliente
		{
			get
			{
				return this._id_turno_cliente;
			}
			set
			{
				if ((this._id_turno_cliente != value))
				{
					this.Onid_turno_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_turno_cliente = value;
					this.SendPropertyChanged("id_turno_cliente");
					this.Onid_turno_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_cliente", DbType="Int NOT NULL")]
		public int cd_cliente
		{
			get
			{
				return this._cd_cliente;
			}
			set
			{
				if ((this._cd_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_clienteChanging(value);
					this.SendPropertyChanging();
					this._cd_cliente = value;
					this.SendPropertyChanged("cd_cliente");
					this.Oncd_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_turno", DbType="Int NOT NULL")]
		public int cd_turno
		{
			get
			{
				return this._cd_turno;
			}
			set
			{
				if ((this._cd_turno != value))
				{
					if (this._Turno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_turnoChanging(value);
					this.SendPropertyChanging();
					this._cd_turno = value;
					this.SendPropertyChanged("cd_turno");
					this.Oncd_turnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Turno_Cliente", Storage="_Cliente", ThisKey="cd_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Turno_Clientes.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Turno_Clientes.Add(this);
						this._cd_cliente = value.id_cliente;
					}
					else
					{
						this._cd_cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turno_Turno_Cliente", Storage="_Turno", ThisKey="cd_turno", OtherKey="id_turno", IsForeignKey=true)]
		public Turno Turno
		{
			get
			{
				return this._Turno.Entity;
			}
			set
			{
				Turno previousValue = this._Turno.Entity;
				if (((previousValue != value) 
							|| (this._Turno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Turno.Entity = null;
						previousValue.Turno_Clientes.Remove(this);
					}
					this._Turno.Entity = value;
					if ((value != null))
					{
						value.Turno_Clientes.Add(this);
						this._cd_turno = value.id_turno;
					}
					else
					{
						this._cd_turno = default(int);
					}
					this.SendPropertyChanged("Turno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nm_cpf;
		
		private string _nm_nome;
		
		private string _nm_login;
		
		private string _nm_senha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnm_cpfChanging(string value);
    partial void Onnm_cpfChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void Onnm_loginChanging(string value);
    partial void Onnm_loginChanged();
    partial void Onnm_senhaChanging(string value);
    partial void Onnm_senhaChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_cpf", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string nm_cpf
		{
			get
			{
				return this._nm_cpf;
			}
			set
			{
				if ((this._nm_cpf != value))
				{
					this.Onnm_cpfChanging(value);
					this.SendPropertyChanging();
					this._nm_cpf = value;
					this.SendPropertyChanged("nm_cpf");
					this.Onnm_cpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_login", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nm_login
		{
			get
			{
				return this._nm_login;
			}
			set
			{
				if ((this._nm_login != value))
				{
					this.Onnm_loginChanging(value);
					this.SendPropertyChanging();
					this._nm_login = value;
					this.SendPropertyChanged("nm_login");
					this.Onnm_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_senha", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string nm_senha
		{
			get
			{
				return this._nm_senha;
			}
			set
			{
				if ((this._nm_senha != value))
				{
					this.Onnm_senhaChanging(value);
					this.SendPropertyChanging();
					this._nm_senha = value;
					this.SendPropertyChanged("nm_senha");
					this.Onnm_senhaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veiculo")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_veiculo;
		
		private int _cd_status;
		
		private string _nm_nome;
		
		private double _capacidade;
		
		private EntityRef<Status_Veiculo> _Status_Veiculo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_veiculoChanging(int value);
    partial void Onid_veiculoChanged();
    partial void Oncd_statusChanging(int value);
    partial void Oncd_statusChanged();
    partial void Onnm_nomeChanging(string value);
    partial void Onnm_nomeChanged();
    partial void OncapacidadeChanging(double value);
    partial void OncapacidadeChanged();
    #endregion
		
		public Veiculo()
		{
			this._Status_Veiculo = default(EntityRef<Status_Veiculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_veiculo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_veiculo
		{
			get
			{
				return this._id_veiculo;
			}
			set
			{
				if ((this._id_veiculo != value))
				{
					this.Onid_veiculoChanging(value);
					this.SendPropertyChanging();
					this._id_veiculo = value;
					this.SendPropertyChanged("id_veiculo");
					this.Onid_veiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_status", DbType="Int NOT NULL")]
		public int cd_status
		{
			get
			{
				return this._cd_status;
			}
			set
			{
				if ((this._cd_status != value))
				{
					if (this._Status_Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncd_statusChanging(value);
					this.SendPropertyChanging();
					this._cd_status = value;
					this.SendPropertyChanged("cd_status");
					this.Oncd_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nm_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nm_nome
		{
			get
			{
				return this._nm_nome;
			}
			set
			{
				if ((this._nm_nome != value))
				{
					this.Onnm_nomeChanging(value);
					this.SendPropertyChanging();
					this._nm_nome = value;
					this.SendPropertyChanged("nm_nome");
					this.Onnm_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidade", DbType="Float NOT NULL")]
		public double capacidade
		{
			get
			{
				return this._capacidade;
			}
			set
			{
				if ((this._capacidade != value))
				{
					this.OncapacidadeChanging(value);
					this.SendPropertyChanging();
					this._capacidade = value;
					this.SendPropertyChanged("capacidade");
					this.OncapacidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Veiculo_Veiculo", Storage="_Status_Veiculo", ThisKey="cd_status", OtherKey="id_status", IsForeignKey=true)]
		public Status_Veiculo Status_Veiculo
		{
			get
			{
				return this._Status_Veiculo.Entity;
			}
			set
			{
				Status_Veiculo previousValue = this._Status_Veiculo.Entity;
				if (((previousValue != value) 
							|| (this._Status_Veiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Status_Veiculo.Entity = null;
						previousValue.Veiculos.Remove(this);
					}
					this._Status_Veiculo.Entity = value;
					if ((value != null))
					{
						value.Veiculos.Add(this);
						this._cd_status = value.id_status;
					}
					else
					{
						this._cd_status = default(int);
					}
					this.SendPropertyChanged("Status_Veiculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
