//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//
//     Modificações neste arquivo podem causar comportamento inadequado e serão perdidas caso
//     o código seja recriado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTRE.Web
{


    public partial class Logout
    {

        /// <summary>
        /// controle de form1.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar mova declaração de campo do arquivo de designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
